
lang: "en-us"

receive-delay: 100
resend-delay: 2400
remove-delay: 200
spawn-distance: 5
courier-entity-type: VILLAGER
blocked-gamemodes: []
blocked-worlds: []


letter:
  # if the creation of anonymous letters is enabled.
  anonymous-letters-enabled: true     # default: true

  # if the letter items will support custom model data
  use-custom-model-data: false        # default: false

  # custom model data of letter items.
  # only works if use-custom-model-data is set to true
  letter-custom-model-data: 0
  anon-letter-custom-model-data: 0