receive-delay: 100
resend-delay: 2400
remove-delay: 200
spawn-distance: 5
courier-entity-type: VILLAGER
blocked-gamemodes: []
blocked-worlds: []


letter:
  anonymous-letters-enabled: true

  use-custom-model-data: false