name: CourierNew
version: 1.3.7
description: A unique mail system
author: Jeremaster101
main: com.joaorihan.courierprime.CourierNew
api-version: 1.14
commands:
  letter:
    description: Create a one-page letter or add pages to an existing letter
    usage: /<command>
  post:
    description: Send a letter to a player(s)
    usage: /<command>
  shred:
    description: Delete a letter you are holding
    usage: /<command>
  shredall:
    description: Delete all letters in your inventory
    usage: /<command>
  unread:
    description: Retreive unread mail
    usage: /<command>
  couriernew:
    description: Help and reload commands
    usage: /<command>
    aliases: [cn]