name: CourierPrime
version: '${version}'
description: A unique mail system
authors: [Jeremaster101, Sentimentos]
main: com.joaorihan.courierprime.CourierPrime
api-version: '26.2'
softdepend: [MythicMobs, ModelEngine]
