package com.joaorihan.courierprime.config;

/**
 * All messages used within the plugin
 *
 * @author Jeremy Noesen
 */
public enum Message {

    PREFIX,
    ANONYMOUS,
    SUCCESS_CREATED_HAND,
    SUCCESS_CREATED_DROPPED,
    SUCCESS_CREATED_ADDED,
    SUCCESS_PAGE_ADDED,
    SUCCESS_PAGE_EDITED,
    SUCCESS_DELETED,
    SUCCESS_DELETED_ALL,
    SUCCESS_SENT_ONE,
    SUCCESS_SENT_MULTIPLE,
    SUCCESS_SENT_ALL,
    SUCCESS_SENT_ALLONLINE,
    SUCCESS_COURIER_ARRIVED,
    SUCCESS_EXTRA_DELIVERIES,
    SUCCESS_IGNORED,
    SUCCESS_RELOADED,
    ERROR_NO_PERMS,
    ERROR_SENT_BEFORE,
    ERROR_NO_MSG,
    ERROR_NO_LETTER,
    ERROR_NOT_YOUR_LETTER,
    ERROR_UNKNOWN_ARGS,
    ERROR_PLAYER_NO_EXIST,
    ERROR_NO_MAIL,
    ERROR_CANT_HOLD,
    ERROR_VANISHED,
    ERROR_WORLD,
    ERROR_GAMEMODE,
    ERROR_IN_BLOCKED_MODE,
    COURIER_NAME,
    COURIER_NAME_RECEIVED,
    LETTER_FROM,
    LETTER_BY,
    PREVIEW_FORMAT,
    PREVIEW_FOOTER,
    DATE_TIME_FORMAT,
    LETTER_TO_ONE,
    LETTER_TO_MULTIPLE,
    LETTER_TO_ALL,
    LETTER_TO_ALLONLINE,
    ENABLE_LETTERS,
    DISABLE_LETTERS,
    HELP_HEADER,
    HELP_LETTER,
    HELP_POST,
    HELP_UNREAD,
    HELP_SHRED,
    HELP_HELP,
    HELP_RELOAD,
    HELP_FOOTER;

}
